### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cicosz** [runetech0/discord-telegram-bot#2]
C:\Users\USER\Downloads\discord-telegram-bot-master>python bot.py
Traceback (most recent call last):
  File "bot.py", line 202, in <module>
    bot.run(config.USER_DISCORD_TOKEN, bot=False)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 640, in run
    return future.result()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 585, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 499, in connect
    await self._connect()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 463, in _connect
    await self.ws.poll_event()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\gateway.py", line 471, in poll_event
    await self.received_message(msg)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\gateway.py", line 425, in received_message
    func(data)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\state.py", line 394, in parse_ready
    guild = self._add_guild_from_data(guild_data)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\state.py", line 274, in _add_guild_from_data
    guild = Guild(data=guild, state=self)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\guild.py", line 177, in __init__
    self._from_data(data)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\guild.py", line 297, in _from_data
    self._sync(guild)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\guild.py", line 328, in _sync
    self._add_channel(CategoryChannel(guild=self, data=c, state=self._state))
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\channel.py", line 726, in __init__
    self._update(guild, data)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\channel.py", line 737, in _update
    self._fill_overwrites(data)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\abc.py", line 294, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'

**Comment by teejayx6** [comment]
> C:\Users\USER\Downloads\discord-telegram-bot-master>python bot.py Traceback (most recent call last): File "bot.py", line 202, in bot.run(config.USER_DISCORD_TOKEN, bot=False) File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 640, in run return future.result() File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 621, in runner await self.start(*args, **kwargs) File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 585, in start await self.connect(reconnect=reconnect) File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 499, in connect await self._connect() File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 463, in _connect await self.ws.poll_event() File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\gateway.py", line 471, in poll_event await self.received_message(msg) File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\gateway.py", line 425, in received_message func(data) File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\state.py", line 394, in parse_ready guild = self._add_guild_from_data(guild_data) File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\state.py", line 274, in _add_guild_from_data guild = Guild(data=guild, state=self) File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\guild.py", line 177, in **init** self._from_data(data) File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\guild.py", line 297, in _from_data self._sync(guild) File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\guild.py", line 328, in _sync self._add_channel(CategoryChannel(guild=self, data=c, state=self._state)) File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\channel.py", line 726, in **init** self._update(guild, data) File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\channel.py", line 737, in _update self._fill_overwrites(data) File "C:\Users\USER\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\abc.py", line 294, in _fill_overwrites self._overwrites.append(_Overwrites(id=overridden_id, **overridden)) TypeError: **new**() got an unexpected keyword argument 'deny_new'

try running as a real bot

**Comment by runetech0** [comment]
Seems like it's something coming from discord.py and not from the bot.
And also I'm not using the discord.py for self bots anymore so I suggest you guys to not use this repo because it may get your tokens disabled quickly.
Hope you understand. Thanks.
